"""Step definitions for features/place_bet.feature."""

from __future__ import annotations

from dataclasses import dataclass, fields
from decimal import Decimal
from typing import Any

from pytest_bdd import given, parsers, scenarios, then, when

from src.api.betting_api import BettingApi, Selection
from src.pages.bet_slip import BetSlip
from src.pages.header import Header
from src.pages.match_list_page import MatchListPage
from src.pages.receipt_modal import Receipt, ReceiptModal
from src.utils.calculations import calculate_payout, to_decimal

scenarios("place_bet.feature")


@dataclass(frozen=True)
class ChosenOutcome:
    """The outcome added to the bet slip, shared between the steps of one scenario."""

    match_name: str
    selection: Selection
    odds: Decimal


@given("the betting page is open")
def betting_page_is_open(match_list_page: MatchListPage) -> None:
    """The match_list_page fixture opens the app."""


@when(
    parsers.parse('the user selects "{selection}" on the nearest upcoming match'),
    target_fixture="outcome",
)
def select_outcome(
    match_list_page: MatchListPage, upcoming_match: dict[str, Any], selection: str
) -> ChosenOutcome:
    chosen = Selection.from_name(selection)
    odds = match_list_page.select_odds(upcoming_match["id"], chosen)
    match_name = f"{upcoming_match['homeTeam']} vs {upcoming_match['awayTeam']}"
    return ChosenOutcome(match_name=match_name, selection=chosen, odds=odds)


@when(parsers.parse("the user enters a stake of {amount}"), target_fixture="stake")
def enter_stake(bet_slip: BetSlip, amount: str) -> Decimal:
    stake = to_decimal(amount)
    bet_slip.enter_stake(stake)
    return stake


@when("the user places the bet")
def place_bet(bet_slip: BetSlip) -> None:
    bet_slip.place_bet()


@when("the user closes the receipt")
def close_receipt(receipt_modal: ReceiptModal) -> None:
    receipt_modal.close()


@then("the bet slip shows the selected match and the potential payout")
def bet_slip_shows_selection(bet_slip: BetSlip, outcome: ChosenOutcome, stake: Decimal) -> None:
    assert bet_slip.selected_match() == outcome.match_name
    assert outcome.selection.capitalize() in bet_slip.selected_market()
    assert bet_slip.potential_payout() == calculate_payout(stake, outcome.odds)


@then("the bet is shown as being placed")
def bet_is_being_placed(bet_slip: BetSlip) -> None:
    assert "placing" in bet_slip.place_bet_label().lower()


@then("the receipt shows the bet details")
def receipt_shows_bet_details(
    receipt_modal: ReceiptModal, outcome: ChosenOutcome, stake: Decimal
) -> None:
    receipt = receipt_modal.read()
    assert receipt.bet_id, "Receipt has no Bet ID"
    assert receipt.placed_at, "Receipt has no placement time"
    # Bet ID and time are generated by the app, so they are taken from the receipt itself.
    expected = Receipt(
        bet_id=receipt.bet_id,
        match=outcome.match_name,
        selection=outcome.selection.capitalize(),
        stake=stake,
        odds=outcome.odds,
        potential_payout=calculate_payout(stake, outcome.odds),
        placed_at=receipt.placed_at,
    )
    differences = [
        f"{field.name}: {getattr(receipt, field.name)!r} != {getattr(expected, field.name)!r}"
        for field in fields(Receipt)
        if getattr(receipt, field.name) != getattr(expected, field.name)
    ]
    assert not differences, "Receipt differs from the bet:\n" + "\n".join(differences)


@then("the bet slip is empty")
def bet_slip_is_empty(bet_slip: BetSlip) -> None:
    assert bet_slip.is_empty()


@then("the balance is reduced by the stake")
def balance_is_reduced(
    header: Header,
    betting_api: BettingApi,
    start_balance: Decimal,
    stake: Decimal,
) -> None:
    expected_balance = start_balance - stake
    assert header.wait_for_balance(expected_balance) == expected_balance
    assert betting_api.get_balance() == expected_balance
